name: Update Profile Widgets
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Contribution Snake
        uses: platane/snk@v3
        with:
          github_user_name: Zoooi9918
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3a7ce2

      - name: Generate Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: dist/achievements.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Zoooi9918
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact

      - name: Generate 3D Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.plugin.isocalendar.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Zoooi9918
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Push to profile-assets branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: profile-assets
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}